version: "1"

services:
    postgres:
        image: postgres:latest
        restart: on-failure
        ports:
            - 5433:5432
        environment:
            POSTGRES_USER: zlplib
            POSTGRES_PASSWORD: zlplibpass
        volumes:
            - postgres:/var/lib/postgresql/data

    pgadmin:
        image: dpage/pgadmin4:latest
        restart: on-failure
        environment:
            PGADMIN_DEFAULT_EMAIL: ranhummer@gmail.com
            PGADMIN_DEFAULT_PASSWORD: zlplibpass
            PGADMIN_LISTEN_PORT: 80
        ports:
            - 15432:80
        volumes:
            - pgadmin:/var/lib/pgadmin
        depends_on:
            - postgres

    server:
        build:
            context: ./src/server
        restart: on-failure
        volumes:
            - server:/server
        ports:
          - 33333:33333
        environment:
          POSTGRES_USER: zlplib
          POSTGRES_PASSWORD: zlplibpass

volumes:
    postgres:
    pgadmin:
    server: